[listen]
host = 'localhost'
port = 8080

[database]
uri = ''

[onslip360]
base = ''         # Onslip 360 environment
realm = ''        # Onslip 360 account
id = ''           # ID of user's API key
key = 'undefined' # User's Base64-encoded API key
