[listen]
port = 8_080
host = "localhost"

[database]
uri = "asdasdasasd"

[onslip360]
base = "asfasfasfasfasd"
realm = "asfsaffffasfasfasd"
id = "fffffffffffffffasfasd"
key = "fffffffffffffffffvxasfasd"
