[listen]
port = 8_080
host = "localhost"

[database]
uri = ""

[onslip360]
base = "https://test.onslip360.com/v1/"
realm = "elis.948636"
id = "key:pat-admin+apielite@elis.948636"
key = "K11Ye3V9dzNvbiguNHVAKVVlKXpSWyoyUTw/UjROaGg="
