[listen]
host  = 'localhost'
port  = 8080

[database]
uri   = 'asfasfasf'

[onslip360]
base  = 'asfasf'      # Onslip 360 environment
realm = 'asfasfasf'                          # Onslip 360 account
id = 'asf' # ID of user's API key
key = 'asfasf'                                    # User's Base64-encoded API key
                